# Jekyll
timezone: Asia/Tokyo
encoding: UTF-8

future: false
show_drafts: false

#relative_permalinks: true

permalink: /blog/:year/:month/:day/:title
#paginate_path: 'page:num'
exclude:
  # general repository files
  - README.md
  - CNAME
  - docs/
  # Docker
  - docker-compose.yml
  - Dockerfile
  # Ruby
  - Gemfile
  - Gemfile.lock
  # Node.js
  - package.json
  - package-lock.json
  - node_modules

markdown: kramdown

url: https://www.natorisana.love
kramdown:
  input: GFM

# Plugins
theme:

plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-avatar
  - jemoji
  - jekyll-mentions

# Plugins Config
## common
title: さなボタン(2)
description: >
  さなボタンをはじめ、
  "バーチャルナース"名取さなと
  そのファンである"せんせえ"方の情報とかコンテンツとかをまとめたり。

# jekyll-github-metadata
repository: sanabutton/sanabutton.github.io

jekyll-mentions:
  base_url: https://twitter.com
